variable "cluster_name" {
  description = "Name of the Talos cluster"
  type        = string
  default     = "barnes-lab"
}

variable "cluster_vip" {
  description = "Virtual IP for the cluster API endpoint"
  type        = string
  default     = "192.168.1.11"
}

variable "kubernetes_version" {
  description = "Kubernetes version"
  type        = string
  default     = "1.35.0"
}

variable "talos_version" {
  description = "Talos version"
  type        = string
  default     = "v1.12.6"
}

variable "nodes" {
  description = "Map of node configurations. Key is used as the hostname."
  type = map(object({
    ip            = string
    role          = string # "controlplane" or "worker"
    install_disk  = string
    storage_disks = optional(list(string))
  }))
  default = {
    "rp5b-cp-01" = {
      ip            = "192.168.1.10"
      role          = "controlplane"
      install_disk  = "/dev/mmcblk0"
      storage_disks = ["/dev/sda", "/dev/sdb"]
    }
    # "cm5-wk-01" = {
    #   ip           = "192.168.1.11"
    #   role         = "worker"
    #   install_disk = "/dev/mmcblk0"
    # }
    # "cm5-wk-02" = {
    #   ip           = "192.168.1.12"
    #   role         = "worker"
    #   install_disk = "/dev/mmcblk0"
    # }
  }
}

# Installer image URLs come from the schematic IDs generated by `make schematics`
# Format: factory.talos.dev/metal-installer/<schematic-id>:<version>
# These are used by Talos when upgrading nodes, not for the initial flash.

variable "talos_image_rp5b" {
  description = "Talos factory installer image for Raspberry Pi 5B (schematic: rp5b with Penta SATA HAT)"
  type        = string
  default     = "factory.talos.dev/metal-installer/ac60af25d2ca703f09730b242d66cbad86146ff38433fcda94f63e668e21f1fe:v1.12.6"
}

variable "talos_image_cm5" {
  description = "Talos factory installer image for Raspberry Pi CM5 (schematic: cm5 on NanoCluster)"
  type        = string
  default     = "factory.talos.dev/metal-installer/b00ac8400b2ad823d3d5e972136dd89c0d960d58e0ff2b12d5b8b87e9d53e670:v1.12.6"
}
